name: Bump package version

on:
  workflow_dispatch:
    inputs:
      bumpLevel:
        description: Type of version bump to implement
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: read

jobs:
  bump_version:
    name: Bump package version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Bump package version and push tag in a Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "DiamondLightSource-build-server"
          git config --global user.email "DiamondLightSource-build-server@users.noreply.github.com"
          git config credential.helper "store --file=.git/credentials"
          echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials

          echo "##[section]Creating commit on branch 'version-bump'"
          git checkout -b version-bump
          yarn version --${{ inputs.bumpLevel }}

          echo "##[section]Creating pull request"
          git push --force --set-upstream origin version-bump
          gh pr create \
            -B main \
            -H version-bump \
            -t "Version update (${{ inputs.bumpLevel }})" \
            -b "This is an automated pull request to update the version."
